
// Note(Leo): This is from the INSTALL.ANY guide in the freetype docs directory.
#include "third_party/freetype/freetype-2.13.3/src/base/ftsystem.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftinit.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftdebug.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftbase.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftbbox.c" 
#include "third_party/freetype/freetype-2.13.3/src/base/ftglyph.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftbdf.c"  
#include "third_party/freetype/freetype-2.13.3/src/base/ftbitmap.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftcid.c"  
#include "third_party/freetype/freetype-2.13.3/src/base/ftfstype.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftgasp.c" 
#include "third_party/freetype/freetype-2.13.3/src/base/ftgxval.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftmm.c"   
#include "third_party/freetype/freetype-2.13.3/src/base/ftotval.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftpatent.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftpfr.c"  
#include "third_party/freetype/freetype-2.13.3/src/base/ftstroke.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftsynth.c"
#include "third_party/freetype/freetype-2.13.3/src/base/fttype1.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftwinfnt.c"
#include "third_party/freetype/freetype-2.13.3/src/base/ftmac.c"


#include "third_party/freetype/freetype-2.13.3/src/bdf/bdf.c"
#include "third_party/freetype/freetype-2.13.3/src/cff/cff.c"
#include "third_party/freetype/freetype-2.13.3/src/cid/type1cid.c"
#include "third_party/freetype/freetype-2.13.3/src/pcf/pcf.c"
#include "third_party/freetype/freetype-2.13.3/src/pfr/pfr.c"
#include "third_party/freetype/freetype-2.13.3/src/sfnt/sfnt.c"
#include "third_party/freetype/freetype-2.13.3/src/truetype/truetype.c"
#include "third_party/freetype/freetype-2.13.3/src/type1/type1.c"
#include "third_party/freetype/freetype-2.13.3/src/type42/type42.c"
#include "third_party/freetype/freetype-2.13.3/src/winfonts/winfnt.c"

#include "third_party/freetype/freetype-2.13.3/src/smooth/smooth.c"
#include "third_party/freetype/freetype-2.13.3/src/raster/raster.c"
#include "third_party/freetype/freetype-2.13.3/src/sdf/sdf.c"

// Note(Leo): This file is omitted from the INSTALL.ANY guide but is required for compilation to succeed
#include "third_party/freetype/freetype-2.13.3/src/svg/ftsvg.c"

#include "third_party/freetype/freetype-2.13.3/src/autofit/autofit.c"
#include "third_party/freetype/freetype-2.13.3/src/cache/ftcache.c"
#include "third_party/freetype/freetype-2.13.3/src/gzip/ftgzip.c"
#include "third_party/freetype/freetype-2.13.3/src/lzw/ftlzw.c"
#include "third_party/freetype/freetype-2.13.3/src/bzip2/ftbzip2.c"
#include "third_party/freetype/freetype-2.13.3/src/gxvalid/gxvalid.c"
#include "third_party/freetype/freetype-2.13.3/src/otvalid/otvalid.c"
#include "third_party/freetype/freetype-2.13.3/src/psaux/psaux.c"
#include "third_party/freetype/freetype-2.13.3/src/pshinter/pshinter.c"
#include "third_party/freetype/freetype-2.13.3/src/psnames/psnames.c"